### ISSUE TITLE
Android builds

### ISSUE THREAD

**Issue by bbbradsmith** [bbbradsmith/hatariB#26]
Try running RetroArch on Android. See what's involved. Theoretically it should be able to build for these platforms.

The libretro/hatari CI build should probably help understand how to compile: https://git.libretro.com/libretro/hatari/-/pipelines

**Comment by DJM75** [comment]
Any progress on this? Would love to see it included in RetroArch for Android.

**Comment by bbbradsmith** [comment]
No work has been done on this, no.

**Comment by DJM75** [comment]
I am trying to compile it for Android but this core, unlike most libretro cores (including the old Hatari core), doesn't use a JNI folder so I can't compile it with RetroArch tools (that would make things a lot easier). So I tried to compile it manually with cmake but it gives me a few errors and the build fails...

> /hatariB/hatari/src/gemdos.c:834:2: error: call to undeclared function 'core_debug_int'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        core_debug_int("GemDOS drives: ",nMaxDrives);

> /hatariB/hatari/src/floppy.c:790:7: error: use of undeclared identifier 'core_prevent_eject_save'
        if (!core_prevent_eject_save)

> /hatariB/hatari/build/src/cpu/libUaeCpu.a: error adding symbols: file in wrong format

**Comment by DJM75** [comment]
I tried to compile it for Android but this core, unlike most libretro cores (including also the old Hatari core), doesn't use a JNI folder with an Android.mk file so I can't compile it with ndk-build (which would make things a lot easier)... So I tried to compile it manually with cmake but I get various errors like the ones below and the build fails:

> /home/djmarco/hatariB/hatari/src/floppy.c: In function ‘Floppy_EjectDiskFromDrive’:
/home/djmarco/hatariB/hatari/src/floppy.c:790:14: error: ‘core_prevent_eject_save’ undeclared (first use in this function)
  790 |         if (!core_prevent_eject_save)

> /home/djmarco/hatariB/hatari/src/gemdos.c:834:2: error: call to undeclared function 'core_debug_int'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        core_debug_int("GemDOS drives: ",nMaxDrives);

**Comment by DJM75** [comment]
I tried to compile it for Android but this core, unlike most libretro cores (including also the old Hatari core), doesn't use a JNI folder with an Android.mk file so I can't compile it with ndk-build (which would make things a lot easier)... So I tried to compile it manually with cmake but I get various errors like this one below and the build fails:

> /home/djmarco/hatariB/hatari/src/floppy.c: In function ‘Floppy_EjectDiskFromDrive’:
/home/djmarco/hatariB/hatari/src/floppy.c:790:14: error: ‘core_prevent_eject_save’ undeclared (first use in this function)
  790 |         if (!core_prevent_eject_save)

**Comment by DJM75** [comment]
I tried to compile it for Android but this core, unlike most libretro cores (including also the old Hatari core), doesn't use a JNI folder with an Android.mk file so I can't compile it with ndk-build (which would make things easier)... So I tried to compile it manually with cmake but I get some errors like this one below and the build fails:

/home/djmarco/hatariB/hatari/src/floppy.c:790:7: error: use of undeclared identifier 'core_prevent_eject_save'
if (!core_prevent_eject_save)

**Comment by DJM75** [comment]
I tried to compile it for Android but this core, unlike most libretro cores (including also the old Hatari core), doesn't use a JNI folder with an Android.mk file so I can't compile it with ndk-build (which would make things a lot easier). So I wanted to try to compile it manually with cmake but I can't see any CMakeLists.txt file... any help?

**Comment by DJM75** [comment]
I tried to compile it for Android but this core, unlike most libretro cores (including also the old Hatari core), doesn't use a JNI folder with an Android.mk file so I can't compile it with ndk-build (which would make things a lot easier). So I tried to compile it manually with cmake and the CMakeLists.txt in the hatari/build directory but after building it with cmake if I execute make I get this error:

> /usr/bin/ld: hatari/build/src/libcore.a: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
make: *** [makefile:124: build/hatarib.so] Error 1

Any help?

**Comment by DJM75** [comment]
I tried to compile it for Android but this core, unlike most libretro cores (including also the old Hatari core), doesn't use a JNI folder with an Android.mk file so I can't compile it with ndk-build (which would make things a lot easier).

So I tried to build it manually with cmake (using the CMakeLists.txt in the hatari directory) but after building it if I execute make I get this error:

/usr/bin/ld: hatari/build/src/libcore.a: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
make: *** [makefile:124: build/hatarib.so] Error 1

Any help?

**Comment by DJM75** [comment]
I tried to compile it for Android but this core, unlike most libretro cores (including also the old Hatari core), doesn't use a JNI folder with an Android.mk file so I can't compile it with ndk-build (which would make things a lot easier).

So I tried to build it manually with cmake (using the CMakeLists.txt in the hatari directory) but after building it if I execute make I get this error:

```
/usr/bin/ld: hatari/build/src/libcore.a: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
make: *** [makefile:124: build/hatarib.so] Error 1
```

Any help?

**Comment by DJM75** [comment]
Ok I tried to compile it for Android but this core, unlike most libretro cores (including also the old Hatari core), doesn't use a JNI folder with an Android.mk file so I can't compile it with ndk-build (which would make things a lot easier).

So I tried a manual build with "cmake" using the CMakeLists.txt in the hatari directory to build or adding my CFLAGS in the "makefile". No matter what, I get the following error when I run a "make":

```
/usr/bin/ld: hatari/build/src/libcore.a: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
make: *** [makefile:124: build/hatarib.so] Error 1
```

Any help?

**Comment by DJM75** [comment]
Ok I tried to compile it for Android but this core, unlike most libretro cores (including also the old Hatari core), doesn't use a JNI folder with an Android.mk file so I can't compile it with ndk-build (which would make things a lot easier).

So I tried a manual build with "cmake" (using the "CMakeLists.txt" file in the "hatari" directory). No luck. Then I also tried to add my CFLAGS in the "makefile" and run a "make". No matter what, I always get the following error:

```
/usr/bin/ld: hatari/build/src/libcore.a: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
make: *** [makefile:124: build/hatarib.so] Error 1
```

Any help?

**Comment by bbbradsmith** [comment]
Are you deleting and rewriting this message over and over? Could you please just edit it instead? I just received 9 e-mail notifications.

**Comment by DJM75** [comment]
Lol sorry about that man, edit didn't work on my phone, now I am on PC.

**Comment by bbbradsmith** [comment]
I don't have any ideas based on the error message you posted. In general each new compiler requires some sort of subtle tweaks to make compatible. At the moment I'm not able to try and set up an android build for this myself, so I can't really follow along directly.

**Comment by DJM75** [comment]
Ok, I will keep trying in the next days and see if I can make it work...

**Comment by DJM75** [comment]
> I don't have any ideas based on the error message you posted. In general each new compiler requires some sort of subtle tweaks to make compatible.

Are the required static libraries ZLIB and SDL2 linked directly to the target program? I ask this because I am using a Linux machine (Ubuntu) to cross compile for Android (arm64). I searched around for my error ("error adding symbols: file in wrong format",  "Relocations in generic ELF (EM: 183)") and that seems to happen when you are trying to link object files or libraries that were compiled for a different architecture or operating system. So maybe the static libraries ZLIB and SDL2 would need to be compiled too for arm64? ...

**Comment by bbbradsmith** [comment]
`make full` is written to compile both ZLIB and SDL2, it does not use pre-existing libraries, so they should be built with the same compiler and settings as everything else.

**Comment by DJM75** [comment]
A bit of progress, I was able to compile it with no errors but I had to fix a line in "floppy.c" because of this error:

```
/home/djmarco/hatariB/hatari/src/floppy.c:790:7: error: use of undeclared identifier 'core_prevent_eject_save'
        if (!core_prevent_eject_save)
```

But now the problem is that the core crashes in RetroArch. I enabled log and I have this error:

`Error(s): dllopen failed: cannot locate symbol "pSdlGuiScrn" referenced by "/data/user/0/com.retroarch.aarch64/cores/hatarib.so"`

We are almost getting there... ;)

**Comment by Uukrull** [comment]
Did you compile it with -D__LIBRETRO__? The errors you are having seems related to that. For example, core_prevent_eject_save is defined here: 

```
#ifdef __LIBRETRO__
extern bool core_savestate_floppy_modify;
static bool core_prevent_eject_save = false;
#endif

```

**Comment by DJM75** [comment]
> Did you compile it with -D__LIBRETRO__? The errors you are having seems related to that. For example, core_prevent_eject_save is defined here:

Yes that was one of the problems (Android NDK doesn't use GCC but Clang and for some reason Clang didn't want to use those CFLAGS). I fixed that and now I have this (hopefully last) error:

`
/home/djm/android-ndk-r26c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android26-clang -o build/hatarib.so -shared  -static-libgcc -Wl,--strip-debug build/core/core.o build/core/core_file.o build/core/core_input.o build/core/core_disk.o build/core/core_config.o build/core/core_osk.o hatari/build/src/libcore.a hatari/build/src/falcon/libFalcon.a hatari/build/src/cpu/libUaeCpu.a hatari/build/src/gui-sdl/libGuiSdl.a hatari/build/src/libFloppy.a hatari/build/src/debug/libDebug.a hatari/build/src/libcore.a /home/djm/hatariB/zlib_build/lib/libz.a -L/home/djm/hatariB/SDL/build/lib /home/djm/hatariB/SDL/build/lib/libSDL2.a -lm -lpthread

ld.lld: error: unable to find library -lpthread
clang-17: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by DJM75** [comment]
> Did you compile it with -D__LIBRETRO__?

Yes, for some reasons Clang (Android NDK doesn't use GCC) didn't want to append any compile CFLAGS set in the makefile. Now I fixed that and everything compiles perfectly. But when I open the core in RetroArch there's a new error (and this time I really have no clue what it is, searching online didn't help)...

`Error(s): dllopen failed: cannot locate symbol "Android_JNI_FileSize" referenced by "/data/user/0/com.retroarch.aarch64/cores/hatarib.so"`

**Comment by DJM75** [comment]
Ok here we go, it was a nightmare trying to understand all the runtime errors that RetroArch gave every time but finally here are the builds for Android. The builds are based on the latest available source (v0.3 unstable) and in the archive there are both 64-bit and 32-bit versions.

**NOTE:** For all those who would like to try the core, a little suggestion... Since on the latest Android versions it's really complicated to access the internal "data" folder where RetroArch stores the cores and the info files, I suggest you to rename the "hatarib.so" file to "hatari_libretro.so" so as to be recognized by RetroArch as the "old" Hatari core (in this way there is no need to copy the .info file, just update the info files from RetroArch's Online Updater). All this while waiting for hatariB to become an official core in RetroArch ;)

Awesome work Brad, this core is really a big step forward compared to the old Hatari 1.8.0 core!

Download:
[hatarib-android--2023-12-20-082452--8cd70b6.zip](https://drive.google.com/file/d/1SBzre4Wk_LrSWCDY5wAH1BElPsBoPAdT/)

**Comment by bbbradsmith** [comment]
Can you document the build steps that were required?

**Comment by DJM75** [comment]
Yes of course.

The real problem with the Android build was understanding how to get to an error-free build by reducing the necessary parameters to the minimum. I had to do hundreds of attempts... it was enough to just set one parameter more (or less) than those required and the build, even if completed without errors, then gave runtime errors on RetroArch. It was a try and try again, Android is a mess and sometimes you also need to try different NDK versions to find the right one for that particular building.

Ok, first of all I made the build on a clean and updated Ubuntu machine (sudo apt update --> sudo apt -y full-upgrade) installing the following packages:

- Make (v4.3) --> sudo apt install make

- CMake (v3.28.3, older versions gave me building errors) --> sudo snap install cmake

- Clang (even if Clang in the NDK toolchain will be used for the building, to compile some files it is also required to install Clang on the machine) --> sudo apt install clang

- UnZip --> sudo apt install unzip

After preparing the environment, the first thing to do is to download the Android NDK (here is the link to the latest version https://dl.google.com/android/repository/android-ndk-r26c-linux.zip ) and unzip it into a folder.

Then I had to modify "makefile.sdl" and set the CFLAGS "--enable-joystick=yes" and "--enable-haptic=yes" (Android requires this or the build will give errors).

And finally here is the script that I wrote with all the steps for a clean building (obviously the paths relating to the NDK needs be modified based on the path where it was installed):

```
###### ARM64-V8A ######
rm -rf build hatari/build SDL zlib zlib_build
export CC=/home/djmarco/android-ndk-r26c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android26-clang

### SDL BUILD ###
# Don't foget to set "--enable-joystick=yes" and "--enable-haptic=yes" in makefile.sdl
export CONFIGURE_FLAGS="--host=aarch64-linux-android"
make -f makefile.sdl

### ZLIB BUILD ###
make -f makefile.zlib

### HATARIB BUILD ###
export CMAKEFLAGS="-DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DCMAKE_ANDROID_NDK=/home/djmarco/android-ndk-r26c -DCMAKE_BUILD_TYPE=Release -DCMAKE_SYSTEM_NAME=Android -DCMAKE_SYSTEM_VERSION=26"
make WERROR=-Wall
```

To build for Android 32-bit (armeabi-v7a) the script is exactly the same, just 3 lines need to be modified:

```
export CC=/home/djmarco/android-ndk-r26c/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi26-clang
export CONFIGURE_FLAGS="--host=armv7a-linux-androideabi"
export CMAKEFLAGS="-DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a -DCMAKE_ANDROID_NDK=/home/djmarco/android-ndk-r26c -DCMAKE_BUILD_TYPE=Release -DCMAKE_SYSTEM_NAME=Android -DCMAKE_SYSTEM_VERSION=26"
```

That's all! ;)

**Comment by Pyman75** [comment]
Firstly may I commend your work on the android build @DJM75 !
I have just run some tests on my Android RA setup and everything seems good so far except floppy saving. Hatarib should write a copy of the disk to "/saves" when saving DATA to the floppy image, such as when saving high scores. This functionality definately works on the windows build. Thanks

**Comment by bbbradsmith** [comment]
Thanks for laying out the steps. I will see what I can do for creating a CI build when I have some time.

**Comment by DJM75** [comment]
> Thanks for laying out the steps. I will see what I can do for creating a CI build when I have some time.

Btw savestates and rewind don't seem to work at all on the Android build (didn't try other platforms).

**Comment by bbbradsmith** [comment]
I suspect that might be the same issue as #28 nobody has yet confirmed whether savestates work on linux, and it may just be that they are only currently working on windows.

**Comment by DJM75** [comment]
> Firstly may I commend your work on the android build @DJM75 ! I have just run some tests on my Android RA setup and everything seems good so far except floppy saving. Hatarib should write a copy of the disk to "/saves" when saving DATA to the floppy image, such as when saving high scores. This functionality definately works on the windows build. Thanks

Hi, I just build the Android version using the source code here. I am not the developer of the original emulator (Hatari) or the libretro core (hatariB) so I can't help you about that.

**Comment by mdvries** [comment]
@DJM75 Thanks for your compiling efforts for Android and @bbbradsmith for all your work on the improved core. I got it running on my Odin 2 android device. However, I run into a problem. Main reason to try was to be able to run IPF images with the core. Where with the official current core it complains that the core build does not support IPF, this core seems to have the support but it complains it can't find the IPF library: Could not load the capsimg 5.1 DLL/SO library. "IPF disk format is unavailable". From what I understand I should put the capsimg.so file in the systemroms directory of Retroarch. I got the file from https://github.com/rsn8887/capsimg/releases and put the capsimg.so in the systemroms directory but for some reason the hatarib core doesn't find it it seems. Any idea what I do wrong?

**Comment by bbbradsmith** [comment]
> From what I understand I should put the capsimg.so file in the systemroms directory of Retroarch.

No, I don't believe it would be able to find or execute it from there. Where does this understanding come from? Were you able to use it with the PUAE core that way?

The best I understand about this I wrote in the [README.md](https://github.com/bbbradsmith/hatariB?tab=readme-ov-file#installation):
> On other platforms it must be installed [in your search path for dlopen](https://linux.die.net/man/8/ldconfig), so if it isn't found next to the SO, maybe try `/usr/lib`? An up to date version of capsimg for many platforms can be downloaded here: [capsimg 5.1 binaries](https://github.com/rsn8887/capsimg/releases)

**Comment by DJM75** [comment]
> Any idea what I do wrong?

Unfortunately Android (12+) **requires** dynamic libraries to be placed to the executable dir, so your phone needs rooting to get the caps library there... My suggestion... don't tuse .ipf ;)

**Comment by mdvries** [comment]
> 

> No, I don't believe it would be able to find or execute it from there. Where does this understanding come from? Were you able to use it with the PUAE core that way?

It was in the instructions of PUAE indeed. The PUAE core does detect the capsimg.so file in the systemroms directory because when I don't have the capsimg.so in that directory it complains it's missing. The binary I got indeed from the site you mention. I must say though that although I don't get the message with PUAE anymore that the library is missing when I put in the library there, somehow the Amiga IPF image doesn't boot.

 

> Unfortunately Android (12+) **requires** dynamic libraries to be placed to the executable dir, so your phone needs rooting to get the caps library there... And yes, PUAE is the same... My suggestion... don't use .ipf ;)

I read about that. Google put extra restrictions on directories. I also have openMSX and that doesn't work anymore with HD images that should be placed in a certain directory. It seems write permissions there are missing. Regretfully currently there is nobody that can do an up to date port and package for Android so that won't be solved I think unless someone is willing to update openMSX with the latest SDK. I am looking for someone who could help out with that so if you would have some spare time and like a challenge....... :)

Some nasty issues have been introduced by google with these new restrictions in permissions for some software.

I read somewhere it is possible to root my Odin 2 device. As I like to play and tweak things to get it working I'll try to root the device too but if HatariB for Android would look for that specific library in the systemroms directory it might work too right? 

Meanwhile I found a great VHD image with Atari ST things (>1GB) to play with and that one worked perfectly with HatariB. So thanks so much for the Android HatariB both.

I'll let you know if I succeed with rooting.

**Comment by bbbradsmith** [comment]
> Btw savestates and rewind don't seem to work at all on the Android build (didn't try other platforms).

Okay, savestates should theoretically be working on latest. ( https://github.com/bbbradsmith/hatariB/commit/80eb831f93095105fcfbca40b4bfe1363bbdafde )

**Comment by DJM75** [comment]
> > Btw savestates and rewind don't seem to work at all on the Android build (didn't try other platforms).
> 
> Okay, savestates should theoretically be working on latest. ( [80eb831](https://github.com/bbbradsmith/hatariB/commit/80eb831f93095105fcfbca40b4bfe1363bbdafde) )

Ok just tried to compile the last build and they still don't work on Android. You save state then when you try to load the state you just saved it reboots the game. ..

**Comment by bbbradsmith** [comment]
Is there anything useful in the log when it reboots? If the savestate failed it should probably at least leave an error message.

**Comment by DJM75** [comment]
> Is there anything useful in the log when it reboots? If the savestate failed it should probably at least leave an error message.

```
[State]: Saving state "/storage/emulated/0/RetroArch/states/hatariB/Paperboy (1989)(Elite).state", 8388632 bytes.
[State]: File already exists. Saving to backup buffer ...
[State]: Loading state "/storage/emulated/0/RetroArch/states/hatariB/Paperboy (1989)(Elite).state", 8388632 bytes.
[State]: Loading state "/storage/emulated/0/RetroArch/states/hatariB/Paperboy (1989)(Elite).state", 8388632 bytes.
[State]: Saving state "RAM", 8388632 bytes.
hatari state save/restore returned with error.
[State]: Failed to load state from "/storage/emulated/0/RetroArch/states/hatariB/Paperboy (1989)(Elite).state".
core_rate_changed
retro_get_system_av_info()
 geometry.base_width = 320
 geometry.base_height = 200
 geometry.aspect_radio = 1.350400
 timing.fps = 60.000000
 timing.sample_rate = 48000.000000
..
..
```

**Comment by bbbradsmith** [comment]
Hm, I'm surprised there isn't anything there. What's the log verbosity level? Is it at 1 (info) or is it fully on at level 0 (debug)?

**Comment by DJM75** [comment]
> Hm, I'm surprised there isn't anything there. What's the log verbosity level? Is it at 1 (info) or is it fully on at level 0 (debug)?

It's the same, I had already tried: This is 0 (debug):

```
[State]: Saving state "/storage/emulated/0/RetroArch/states/hatariB/International Karate + (1988)(System 3)[b].state", 8388632 bytes.
[State]: Loading state "/storage/emulated/0/RetroArch/states/hatariB/International Karate + (1988)(System 3)[b].state", 8388632 bytes.
[State]: Saving state "RAM", 8388632 bytes.
hatari state save/restore returned with error.
[State]: Failed to load state from "/storage/emulated/0/RetroArch/states/hatariB/International Karate + (1988)(System 3)[b].state".
core_rate_changed
..
..
```

**Comment by DJM75** [comment]
> Also, in the core options, under Advanced, there's a setting for "Hatari Logging" which might help if it isn't already on.

Now it's set on "Error". Can I try to change it to "Debug" (the options are: Fatal, Error, Warn, Info, To Do, Debug)?

**Comment by bbbradsmith** [comment]
I've been setting up a CI build for this and it's almost ready: #36 

A couple of build notes from some comparison testing: https://github.com/bbbradsmith/hatariB/actions/runs/8590840383

`-DCMAKE_BUILD_TYPE=Release` does make a minor difference, as cmake adds an extra `-O2` by default, overriding the `-O3` already on the line, but with this set it gets `-O3`. I might want to add this to all the builds, actually.

`-DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake` is officially recommended, but I found that it completely overrides the environment $CFLAGS which is a problem (many people have reported this as a bug, because it was an append in older versions of cmake, there were some interesting arguments). Anyway, aside from the override I didn't see it producing anything different in the command line, except it wanted `-mthumb` on the 32-bit version, which seemed inappropriate anyway. My understanding is that generally `-mthumb` favours size and `-marm` (the default) favours speed.

**Comment by bbbradsmith** [comment]
Okay, I've got the CI running on the main branch. I have not been able to test the binaries produced yet, but in theory we have android builds now. Thanks for the help. :)

**Comment by DJM75** [comment]
> Okay, I've got the CI running on the main branch. I have not been able to test the binaries produced yet, but in theory we have android builds now. Thanks for the help. :)

Thanks to you, Brad! ;) Anyways I tested the build and it work (still the savestate problem but that's another thing).

**Comment by bbbradsmith** [comment]
Okay, I think I solved the savestate problem: https://github.com/bbbradsmith/hatariB/commit/91cd035b4a8b85921a4c02ec4222d7db499c6a37

Please let me know if that fixes it for you, too.

Looks like I accidentally used `extern int` where I needed an `extern bool` and somehow this hasn't manifested as a noticeable error on any other platform. Is `bool` a byte on Android? I'm really surprised the linker wasn't able to catch this as an error though.

Otherwise, I finally figured out how to get the core onto my phone (a 32-bit system).
1. Install Retroarch Plus from the google play store, run it to set up the initial directories. Set the downloads directory if needed somewhere specific.
2. Copy the `.so` to the retroarch downloads folder, then go to Load Core > Install or Restore a Core. Per DJM75's advice, it's a good idea to rename it to `hatari.so`, to piggy back on its existing `.info` because there seems to be no way to send the a new one without root access. Because of an oversight of the UI, without an `.info` you also can't delete a core either.

I was hoping to be able to test in Android Studio's emulator as well, but I can't seem to get it to accept any input. There seems to be no gamepad interface, and whatever it's doing for keyboard input isn't recognized properly by RetroArch. After launching it, I can tap one main menu item once and it will highlight it, but I couldn't go any further, it just seemed locked up at that point. Anyone else ever had any luck with this?

**Comment by bbbradsmith** [comment]
I guess the way to get both the `.info` and `capsimg.so` working would be to build RetroArch itself, and add them to the APK you created, but I haven't taken the effort to try at this point.

**Comment by DJM75** [comment]
Awesome Brad, now savestates (and rewind too) work fine on the Android build ;)

As a side note, I suggest to not install RetroArch from the Play Store, that's an old version of 3 years ago, better to install the last .apk (stable or nightly) downloading it from the RetroArch site.

About deleting a core without an .info file, it's still possible if you go to "Settings -> Core - Manage Cores" (yes, it's well hidden in RetroArch UI) ;)

**Comment by bbbradsmith** [comment]
Thanks for testing it. :)

Yeah, I was trying out both versions. I'd agree the latest APK is better, but it still works fine with the one on the Play store too.

>  The alternative is to change the path pointing to the RetroArch .info file directory to a directory accessible in Android and copy manually the .info file there

Ah! I didn't realize that would work. I wasn't sure because it was one of the things hidden in the private data area. I notice the  online updater seems to silently fail to download core info, maybe they just decided to put it inside the APK as a workaround, and just leave it there.

> (unfortunately it is not possible to change the path of the cores, the latest versions of Android do not allow this).

Yeah, that seems sensible, though, especially since they provided the download option to sideload them. I was just hoping I could get capsimg.so in there the same way, but I'm guessing it probably needs to be inside the APK lib path to work.

Maybe someday someone will write a compatible open IPF emulation and we won't have to deal with this issue. :S

> About deleting a core without an .info file, it's still possible if you go to "Settings -> Core - Manage Cores" (yes, it's well hidden in RetroArch UI) ;)

Ah, thank you! I didn't realize there was a Core settings! I wonder when that was added... probably a long time ago, heh.

I'll add some Android setup notes to the readme.

**Comment by bbbradsmith** [comment]
Closing this as complete. :) If there's further comments feel free to leave them here, or start a new issue if needed.
