### ISSUE TITLE
Expose --auto through M3U

### ISSUE THREAD

**Issue by bbbradsmith** [bbbradsmith/hatariB#30]
An idea I mentioned in the [Atari-Forum thread](https://www.atari-forum.com/viewtopic.php?p=455293#p455293) about: #29

Could use an extended M3U format to pass an argument as the `--auto` parameter to Hatari, allowing automatic start of a program on boot.

One of the goals is allowing a single hard disk image to be auto-started by many different M3Us, like this:
```
#EXTM3U
#AUTO:C:\XENON2\XENON2.PRG
games.ahd
# could optionally include floppy disks
diska.st
diskb.st
```

I think this also addresses some of the goals from #12

**Comment by bbbradsmith** [comment]
Now supported in: https://github.com/bbbradsmith/hatariB/commit/78d4faec3cc7c8a0d6d27d9ca04466120456aa87

**Comment by DarkCTO** [comment]
Where is this C:\ drive?
What if I want to run a prog directly from A: ?
