### ISSUE TITLE
Notification switch off/ "Unable to save memory state to file" problem

### ISSUE THREAD

**Issue by msrecko** [bbbradsmith/hatariB#32]
Hi, 
how cand be switched off some notification (libretro: hatari v.0.2, in RA 1.15) or to solve "Unable to save memory state to file" problem?

Im, teting HatariB in Batocera v38, btw.

![HatariBNotifications](https://github.com/bbbradsmith/hatariB/assets/52575728/3523ddd2-f8e5-4b86-98b0-9c2f6424e55e)

**Comment by bbbradsmith** [comment]
The stronger question I have is: do savestates work at all for you?

I had one report that savestate files were coming out empty in the Linux build (a different distro), but I have not yet investigated it firsthand. I wasn't sure if it affected Linux universally or just the one reporter's machine.

This is one of the goals of open issue #28

**Comment by bbbradsmith** [comment]
I believe this is fixed in the latest (as of: https://github.com/bbbradsmith/hatariB/commit/c04223e073dfabdc952e1c86c72d158d1c90f75e )

Savestates should now work on all platforms, I hope.

**Comment by bbbradsmith** [comment]
I had already suppressed the boot notification at first startup, but I added an option to disable it entirely if wanted, in the Video options: https://github.com/bbbradsmith/hatariB/commit/01b356f35d3d55371a93cd0cf990fc76a9e7fbf2
