### ISSUE TITLE
Hatari 2.5 integration

### ISSUE THREAD

**Issue by bbbradsmith** [bbbradsmith/hatariB#42]
It seems that Hatari 2.5 will release soon. I think integrating this might be my last major task before considering this ready to leave the beta state.

After doing this, remember to check on the Spectre example in #37 to see if that is now supported. (Edit: it works!)

**Comment by bbbradsmith** [comment]
First pass merged as of [03bf35f](https://github.com/bbbradsmith/hatariB/commit/03bf35f0e4effed8b64d69823985e458cd48ec0f)

Things to follow up on:
* Are there new settings worth picking up from configuration.h
* 16-bit rendering support is gone, make sure it reports this to libretro, remove unneeded code from OSK
* KP_LEFTPARAM / KP_RIGHTPARAM were added to the keymap, check if that's relevant to my other keyboard improvement project.

**Comment by bbbradsmith** [comment]
To study the hatariB changeset vs. the 2.5.0 source:
https://github.com/bbbradsmith/hatariB/compare/main..unmerged-2.5.0

For reference, the hatariB changeset in 0.3 vs. the 2.4.1 source:
https://github.com/bbbradsmith/hatariB/compare/0.3..unmerged-2.4.1

(If curious, this feature can be found by putting /compare after the base URL of the repository, which gives a menu to select 2 branches. The eventual URL will have ... in the middle which compares changes since the last common branch? However, if you shorten it to .. you get a file to file comparison which is what we want here. [GitHub Docs reference](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-comparing-branches-in-pull-requests))

**Comment by DJM75** [comment]
Great job Brad! I did some quick testing with the new Android build and everything seems to work fine (including save states, but of course old 2.4.1 save states are not compatible). I will continue to test and see if I notice anything strange... ;) When do you plan to integrate floppy disk drive sound simulation into the official build (love that, it really gives that "retro vibe") ?

**Comment by bbbradsmith** [comment]
The drive sound is something I will get to, haven't worked on it yet.

**Comment by bbbradsmith** [comment]
Okay, I think this passes my first round of tests now. Only really found 2 things to take care of:
* `SCC_UnInit` was crashing when closing the second game due to a new uninitialized file handle.
* sound.c had a new variable `YM2149_Freq_div_2` that should have been in the savestate.
