### ISSUE TITLE
Run m3u from zip without extracting?

### ISSUE THREAD

**Issue by DarkCTO** [bbbradsmith/hatariB#44]
For DOS there is dosbox pure, that could mount a zip and auto-run dosbox.conf
hatariB supporting zip format and auto-run m3u, so would this be possible?

**Comment by bbbradsmith** [comment]
So, the idea is that there is exactly one M3U inside a ZIP, and then the M3U must reference the ZIP's contents instead of the normal filesystem?

I'm not sure if this would be a small amount, or a huge amount of work. I'll try to take a look at it.

**Comment by DarkCTO** [comment]
Yes, it can extract to a temp folder, or mount, but leaving original archive intact, a look at C64 dreams game.bat
We don't have to support .bat language, but using m3u with #auto with all files inside the zip will allow 1 file per game.

Generic game.bat from c64 dreams project
```
start ..\..\Retroarch\Controller.exe

for %%I in (.) do set folder=%%~nxI
set manual="%folder% Manual.cbz"
set pdf="%folder% Manual.pdf"
set cmd="%folder%.cmd"
set m3u="%folder%.m3u"
set crt="%folder%.crt"
set d81="%folder%.d81"

if exist %manual% (
start ..\..\Retroarch\Manuals.exe
start ..\..\Utilities\Cdisplayex\Cdisplayex.exe %manual%
)

if exist %pdf% (
start ..\..\Retroarch\Manuals.exe
start ..\..\Utilities\Cdisplayex\Cdisplayex.exe %pdf%
)

REM Timeout 1

if exist %cmd% (
..\..\Retroarch\Retroarch.exe -L "..\..\Retroarch\cores\vice_x64_libretro.dll" %cmd%
)

if exist %m3u% (
..\..\Retroarch\Retroarch.exe -L "..\..\Retroarch\cores\vice_x64_libretro.dll" %m3u%
)

if exist %crt% (
..\..\Retroarch\Retroarch.exe -L "..\..\Retroarch\cores\vice_x64_libretro.dll" %crt%
)

if exist %d81% (
..\..\Retroarch\Retroarch.exe -L "..\..\Retroarch\cores\vice_x64_libretro.dll" %d81%
)
```

**Comment by bbbradsmith** [comment]
Okay, I've added this to the latest build. The catch is that the ZIP has to be renamed to **ZST** to work.

The ZIP extension could not be used for this, because RetroArch will automatically unpack the first file and give that to the core. There's no way to load a file that ends with .ZIP directly by the core. However, renaming it to something else is just fine.

**Comment by DarkCTO** [comment]
![2024-05-01-152858_1706x1053_scrot](https://github.com/bbbradsmith/hatariB/assets/99158109/f85886d4-3524-4b20-92d9-2a0264b3fcbb)

OK So I got one file to test

This is the content of the m3u
```
Afterburner (1988)(Activision)(Disk 1 of 2).stx
Afterburner (1988)(Activision)(Disk 2 of 2).stx
```
I'm still struggling as I downloaded the ubuntu version and rename it to hatari_libretro.so but the original hatari doesn't support zst format

**Comment by bbbradsmith** [comment]
Instead of trying to rename it like that, copy the info files in the zip to your core info directory, which will tell RetroArch what kind of files are supported.

**Comment by DarkCTO** [comment]
Can confirm this works. Hope it wasn't much trouble. Thank you.

**Comment by bbbradsmith** [comment]
RetroArch treats zips as special, and the cores can't get around it, unfortunately. It's RetroArch that extracts only one file from it.

**Comment by DarkCTO** [comment]
![Peek 2024-05-01 21-56](https://github.com/bbbradsmith/hatariB/assets/99158109/377b7082-66ad-4d55-bfa5-a323c8c25a5a)

Interestingly, Vice for C64 works with zip format. I recorded a demonstration. You may find it interesting.

**Comment by bbbradsmith** [comment]
That is very strange. I wonder how it is done? Maybe they do something sneaky to find out the path of the ZIP file and just load it behind RetroArch's back?

**Comment by bbbradsmith** [comment]
Okay, thanks for pointing that out. There was a "block_extract" option that could be used, but I had to figure out another setting needed for it to work (undocumented). I think it is now able to load ZIPs directly now, and I have removed the ZST workaround. Could you give it another try?

**Comment by DarkCTO** [comment]
It seems to work. However, to be fully equivalent, could it auto-run the first line in m3u?

**Comment by DarkCTO** [comment]
![Peek 2024-05-01 21-56](https://github.com/bbbradsmith/hatariB/assets/99158109/fe67448d-a414-42e5-93a2-5342aae0eb8e)


See the recorded demo
Selecting Disk 1 will boot the game automatically
But selecting the zip contains the m3u and 3 disks will just boot to desktop, clicking on floppy disks will just give me errrors

**Comment by DarkCTO** [comment]
![Peek 2024-05-01 21-56](https://github.com/bbbradsmith/hatariB/assets/99158109/eb0f0cca-af36-47ac-b00f-e7612b1b0ea8)

On a closer look, the zip files will show 3 disks, but they are all missing

**Comment by bbbradsmith** [comment]
It looks like the problem is that in the M3U the filenames are misspelled with a - between Armour and Gedden.

**Comment by DarkCTO** [comment]
![2024-05-02-085309_1278x236_scrot](https://github.com/bbbradsmith/hatariB/assets/99158109/171259b4-e7ad-43ac-8e8a-8a43372afb17)

I copied and pasted the filenames from file explorer to m3u so I'm sure they match.

**Comment by bbbradsmith** [comment]
Ah, I see. Yes, I had not considered putting the M3U inside a folder in the ZIP. All paths were assumed relative to the root of the zip. The disk files should still be able to work in the M3U with a / but let me see if it isn't hard to pick up the M3U's path inside the ZIP.

**Comment by DarkCTO** [comment]
Yes, thank you for the explanation. As I said, I'm 100% satisfied with what we are having.

If you do implement folder as root, please also make sure files as root also works.

**Comment by bbbradsmith** [comment]
Yes, they still run from the root of the ZIP as well. Either will work the same.
